#IP=10.2.0.23
IP=10.2.0.24
#IP=10.2.0.30
PORT=502
#Configurare in base al dispositivo
#MAX_RELAYS=15 #indicare 7 (da 0 a 7) per 8 uscite oppure 15 (da 0 a 15) per 16 uscite
MAX_IN=7
#MAX_IN=15
MAX_RELAYS=7 #indicare 7 (da 0 a 7) per 8 uscite oppure 15 (da 0 a 15) per 16 uscite
